# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types: [ pre-commit ]
default_language_version:
  python: python3.13
default_stages: [ pre-commit, pre-push ]
files: ''
exclude: ^$
fail_fast: false
minimum_pre_commit_version: 3.3.3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-use-type-annotations
      - id: python-no-log-warn
      - id: python-no-eval
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [ --config=pyproject.toml ]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.2.0
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [ --settings-path=pyproject.toml ]
