[tool.poetry]
name = "nhm-django-infra"
version = "0.1.0"
description = ""
authors = ["xuheng.zong <xuheng.zong2@dbappsecurity.com.cn>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
django = "^5.1.5"
dynaconf = "^3.2.7"
djangorestframework = "^3.15.2"
django-filter = "^24.3"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.1.0"

[tool.black]
line_length = 120

[tool.isort]
profile = "black"
src_paths = ["isort", "test"]
py_version = 313
skip_gitignore = true
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_first_party = ["porsche"]
multi_line_output = 3
line_length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"