services:
  postgres:
    image: postgres:17.6-bookworm
    container_name: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - "$PWD/postgres/data:/var/lib/postgresql/data"
      - "$PWD/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "$PWD/postgres/postgres.conf:/etc/postgresql/postgresql.conf"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_INITDB_ARGS: $POSTGRES_INITDB_ARGS
    networks:
      - default

networks:
  default:
    name: nhm-django-infra-network
    driver: bridge
