services:
  postgres:
    image: postgres:17.6-bookworm
    container_name: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - "$PWD/postgres/data:/var/lib/postgresql/data"
      - "$PWD/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "$PWD/postgres/postgres.conf:/etc/postgresql/postgresql.conf"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_INITDB_ARGS: $POSTGRES_INITDB_ARGS
    networks:
      - default

  nhm-django-infra:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    image: nhm-django-infra:${PORSCHE_VERSION:-latest}
    container_name: nhm-django-infra
    restart: always
    ports:
      - "8000:8000"
    environment:
      PORSCHE_VERSION: $PORSCHE_VERSION
      PORSCHE_DATABASES__default__DB: $PORSCHE_DATABASES__default__DB
      PORSCHE_DATABASES__default__USER: $PORSCHE_DATABASES__default__USER
      PORSCHE_DATABASES__default__PASSWORD: $PORSCHE_DATABASES__default__PASSWORD
      PORSCHE_DATABASES__default__HOST: $PORSCHE_DATABASES__default__HOST
      PORSCHE_DATABASES__default__PORT: $PORSCHE_DATABASES__default__PORT
    networks:
      - default
    depends_on:
      - postgres

networks:
  default:
    name: nhm-django-infra-network
    driver: bridge
