# Generated by Django 5.2.4 on 2025-09-09 09:09

import uuid

import django.db.models.deletion
from django.db import migrations, models

import porsche.core.django.db.models.fields.related


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name="唯一标识")),
                ("name", models.CharField(max_length=100, verbose_name="公司名称")),
            ],
            options={
                "default_related_name": "company",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name="唯一标识")),
                ("name", models.CharField(max_length=20, verbose_name="标签名称")),
                ("category", models.CharField(max_length=20, verbose_name="标签类型")),
            ],
            options={
                "default_related_name": "tag",
            },
        ),
        migrations.CreateModel(
            name="CompanyTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name="唯一标识")),
                (
                    "company",
                    porsche.core.django.db.models.fields.related.PorscheForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="porsche.company",
                        to_field="uid",
                        verbose_name="公司",
                    ),
                ),
                (
                    "tag",
                    porsche.core.django.db.models.fields.related.PorscheForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="porsche.tag",
                        to_field="uid",
                        verbose_name="标签",
                    ),
                ),
            ],
            options={
                "default_related_name": "company_tag",
            },
        ),
    ]
