# Generated by Django 5.2.4 on 2025-09-02 07:56

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("porsche", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name="唯一标识")),
                ("name", models.CharField(max_length=20, verbose_name="标签名称")),
                ("category", models.CharField(max_length=20, verbose_name="标签类型")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=100, verbose_name="公司名称"),
        ),
    ]
