# Generated by Django 5.2.4 on 2026-01-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("porsche", "0002_role_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.FileField(null=True, upload_to="avatar", verbose_name="头像"),
        ),
    ]
