# Generated by Django 5.2.4 on 2025-09-02 09:12

import uuid

import django.db.models.deletion
from django.db import migrations, models

import porsche.core.django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ("porsche", "0002_tag_alter_company_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name="唯一标识")),
                (
                    "company",
                    porsche.core.django.db.models.fields.related.PorscheForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company",
                        to="porsche.company",
                        to_field="uid",
                        verbose_name="公司",
                    ),
                ),
                (
                    "tag",
                    porsche.core.django.db.models.fields.related.PorscheForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag",
                        to="porsche.tag",
                        to_field="uid",
                        verbose_name="标签",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
