# Generated by Django 5.2.4 on 2025-09-03 08:52

import django.db.models.deletion
from django.db import migrations

import porsche.core.django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ("porsche", "0003_companytag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"default_related_name": "company"},
        ),
        migrations.AlterModelOptions(
            name="companytag",
            options={"default_related_name": "company_tag"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"default_related_name": "tag"},
        ),
        migrations.AlterField(
            model_name="companytag",
            name="company",
            field=porsche.core.django.db.models.fields.related.PorscheForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="porsche.company",
                to_field="uid",
                verbose_name="公司",
            ),
        ),
        migrations.AlterField(
            model_name="companytag",
            name="tag",
            field=porsche.core.django.db.models.fields.related.PorscheForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="porsche.tag",
                to_field="uid",
                verbose_name="标签",
            ),
        ),
    ]
