name: "Run Coverage And Generate Badge"
on:
  push:
    branches: [
      "main",
      "action/*",
    ]
    paths:
      - "src/**"
      - ".github/workflows/coverage.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "src/**"
      - ".github/workflows/coverage.yml"
    types:
      - "opened"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  coverage-run-and-genbadge:
    name: "coverage run, coverage xml and genbadge"
    runs-on: [
      "ubuntu-latest"
    ]
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v5.0.0"
      - name: "Install Uv"
        uses: "astral-sh/setup-uv@v6"
        with:
          version: "latest"
          activate-environment: true
          python-version: "3.13"
          working-directory: "."
      - name: "uv sync"
        run: |
          uv --version
